<?php
/**
 * Plugin Name: Pulpcovers Modified Posts Feed
 * Plugin URI: https://pulpcovers.com/
 * Description: Creates a dedicated RSS feed of recently modified posts, ordered by last modified date.
 * Version: 1.0.1
 * Author: Pulpcovers
 * Author URI: https://pulpcovers.com/
 * License: CC0-1.0
 * Text Domain: pulpcovers-modified-posts-feed
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Pulpcovers_Modified_Posts_Feed {

    public function __construct() {
        add_action( 'init', array( $this, 'init_feed' ) );
        add_action( 'admin_menu', array( $this, 'add_settings_page' ) );
        add_action( 'admin_init', array( $this, 'register_settings' ) );
        add_action( 'admin_notices', array( $this, 'admin_notices' ) );
        add_action( 'update_option_modified_posts_feed_cache_enabled', array( $this, 'maybe_clear_cache' ), 10, 2 );
        add_action( 'update_option_modified_posts_feed_index_enabled', array( $this, 'maybe_update_index' ), 10, 2 );
    }

    public function init_feed() {
        $slug = get_option( 'modified_posts_feed_slug', 'modified-posts' );

        add_feed( $slug, array( $this, 'render_feed' ) );
    }

    public function render_feed() {
        header( 'Content-Type: application/rss+xml; charset=' . get_option( 'blog_charset' ), true );

        $cache_enabled = get_option( 'modified_posts_feed_cache_enabled', false );
        $cache_key     = 'modified_posts_feed_cache';

        if ( $cache_enabled ) {
            $cached = get_transient( $cache_key );
            if ( $cached ) {
                // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Cached RSS XML generated by this plugin.
                echo $cached;
                return;
            }
        }

        $post_types = get_option( 'modified_posts_feed_post_types', array( 'post' ) );
        $limit      = intval( get_option( 'modified_posts_feed_limit', 10 ) );

        $args = array(
            'post_type'      => $post_types,
            'posts_per_page' => $limit,
            'orderby'        => 'modified',
            'order'          => 'DESC',
            'post_status'    => 'publish',
        );

        $query = new WP_Query( $args );

        ob_start();
        echo '<?xml version="1.0" encoding="' . esc_attr( get_option( 'blog_charset' ) ) . '"?>';
        ?>
<rss version="2.0"
    xmlns:media="http://search.yahoo.com/mrss/"
>
<channel>
    <title><?php bloginfo_rss( 'name' ); ?> - <?php esc_html_e( 'Recently Modified Posts', 'pulpcovers-modified-posts-feed' ); ?></title>
    <link><?php bloginfo_rss( 'url' ); ?></link>
    <description><?php esc_html_e( 'A feed of recently modified posts.', 'pulpcovers-modified-posts-feed' ); ?></description>
    <language><?php bloginfo_rss( 'language' ); ?></language>
    <lastBuildDate><?php echo esc_html( mysql2date( 'D, d M Y H:i:s +0000', get_lastpostmodified( 'GMT' ), false ) ); ?></lastBuildDate>

    <?php while ( $query->have_posts() ) : $query->the_post(); ?>
        <item>
            <title><?php the_title_rss(); ?></title>
            <link><?php the_permalink_rss(); ?></link>
            <pubDate><?php echo esc_html( mysql2date( 'D, d M Y H:i:s +0000', get_post_modified_time( 'Y-m-d H:i:s', true ), false ) ); ?></pubDate>
            <guid isPermaLink="false"><?php the_guid(); ?></guid>
            <description><![CDATA[<?php the_excerpt_rss(); ?>]]></description>

            <?php if ( get_option( 'modified_posts_feed_featured_image', false ) ) : ?>
                <?php if ( has_post_thumbnail() ) :
                    $image = wp_get_attachment_image_src( get_post_thumbnail_id(), 'full' );
                    if ( $image ) : ?>
                        <media:content url="<?php echo esc_url( $image[0] ); ?>" medium="image" />
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </item>
    <?php endwhile; wp_reset_postdata(); ?>

</channel>
</rss>
        <?php

        $output = ob_get_clean();

        if ( $cache_enabled ) {
            set_transient( $cache_key, $output, HOUR_IN_SECONDS );
        }
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- RSS XML output generated by this plugin.
        echo $output;
    }

    public function add_settings_page() {
        add_options_page(
            __( 'Pulpcovers Modified Posts Feed Settings', 'pulpcovers-modified-posts-feed' ),
            __( 'Pulpcovers Modified Posts Feed', 'pulpcovers-modified-posts-feed' ),
            'manage_options',
            'pulpcovers-modified-posts-feed',
            array( $this, 'render_settings_page' )
        );
    }

    public function register_settings() {
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_slug',
            array(
                'type'              => 'string',
                'sanitize_callback' => 'sanitize_title',
                'default'           => 'modified-posts',
            )
        );
    
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_limit',
            array(
                'type'              => 'integer',
                'sanitize_callback' => 'absint',
                'default'           => 10,
            )
        );
    
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_post_types',
            array(
                'type'              => 'array',
                'sanitize_callback' => array( $this, 'sanitize_post_types' ),
                'default'           => array( 'post' ),
            )
        );
    
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_cache_enabled',
            array(
                'type'              => 'boolean',
                'sanitize_callback' => array( $this, 'sanitize_checkbox' ),
                'default'           => false,
            )
        );
    
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_featured_image',
            array(
                'type'              => 'boolean',
                'sanitize_callback' => array( $this, 'sanitize_checkbox' ),
                'default'           => false,
            )
        );
    
        register_setting(
            'modified_posts_feed_settings',
            'modified_posts_feed_index_enabled',
            array(
                'type'              => 'boolean',
                'sanitize_callback' => array( $this, 'sanitize_checkbox' ),
                'default'           => false,
            )
        );
    }


    public function admin_notices() {
        settings_errors( 'modified_posts_feed_messages' );
    }

    public function render_settings_page() {
        ?>
        <div class="wrap">
            <h1><?php esc_html_e( 'Pulpcovers Modified Posts Feed Settings', 'pulpcovers-modified-posts-feed' ); ?></h1>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'modified_posts_feed_settings' );
                do_settings_sections( 'modified_posts_feed_settings' );
                ?>

                <table class="form-table">

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Feed URL Slug', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <input type="text" name="modified_posts_feed_slug" value="<?php echo esc_attr( get_option( 'modified_posts_feed_slug', 'modified-posts' ) ); ?>" />
                            <p class="description"><?php esc_html_e( 'The slug used for the feed URL.', 'pulpcovers-modified-posts-feed' ); ?></p>
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Posts Per Page', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <input type="number" name="modified_posts_feed_limit" value="<?php echo esc_attr( get_option( 'modified_posts_feed_limit', 10 ) ); ?>" />
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Post Types', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <?php
                            $post_types = get_post_types( array( 'public' => true ), 'objects' );
                            $selected   = (array) get_option( 'modified_posts_feed_post_types', array( 'post' ) );

                            foreach ( $post_types as $type ) :
                                ?>
                                <label>
                                    <input type="checkbox" name="modified_posts_feed_post_types[]" value="<?php echo esc_attr( $type->name ); ?>" <?php checked( in_array( $type->name, $selected, true ) ); ?> />
                                    <?php echo esc_html( $type->labels->singular_name ); ?>
                                </label><br>
                            <?php endforeach; ?>
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Enable Caching', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <input type="checkbox" name="modified_posts_feed_cache_enabled" value="1" <?php checked( get_option( 'modified_posts_feed_cache_enabled', false ) ); ?> />
                            <p class="description"><?php esc_html_e( 'Caches the feed output for one hour.', 'pulpcovers-modified-posts-feed' ); ?></p>
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Include Featured Images', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <input type="checkbox" name="modified_posts_feed_featured_image" value="1" <?php checked( get_option( 'modified_posts_feed_featured_image', false ) ); ?> />
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php esc_html_e( 'Add Database Index', 'pulpcovers-modified-posts-feed' ); ?></th>
                        <td>
                            <input type="checkbox" name="modified_posts_feed_index_enabled" value="1" <?php checked( get_option( 'modified_posts_feed_index_enabled', false ) ); ?> />
                            <p class="description"><?php esc_html_e( 'Adds an index on post_modified for performance.', 'pulpcovers-modified-posts-feed' ); ?></p>
                        </td>
                    </tr>

                </table>

                <?php submit_button(); ?>
            </form>
        </div>
        <?php
    }

    public function maybe_clear_cache( $old, $new ) {
        if ( ! $new ) {
            delete_transient( 'modified_posts_feed_cache' );
            add_settings_error(
                'modified_posts_feed_messages',
                'cache_cleared',
                __( 'Cache cleared successfully!', 'pulpcovers-modified-posts-feed' ),
                'success'
            );
        }
    }

    public function maybe_update_index( $old, $new ) {
        global $wpdb;

        $table = $wpdb->posts;

        if ( $new ) {
            $wpdb->query( "ALTER TABLE $table ADD INDEX modified_posts_feed_idx (post_modified)" );
            add_settings_error(
                'modified_posts_feed_messages',
                'index_added',
                __( 'Database index added successfully!', 'pulpcovers-modified-posts-feed' ),
                'success'
            );
        } else {
            $wpdb->query( "ALTER TABLE $table DROP INDEX modified_posts_feed_idx" );
            add_settings_error(
                'modified_posts_feed_messages',
                'index_removed',
                __( 'Database index removed.', 'pulpcovers-modified-posts-feed' ),
                'success'
            );
        }
    }
    public function sanitize_post_types( $value ) {
    if ( ! is_array( $value ) ) {
        return array();
    }

    $value = array_map( 'sanitize_key', $value );

    $public_types = get_post_types( array( 'public' => true ) );
    $value        = array_intersect( $value, $public_types );

    return $value;
}

public function sanitize_checkbox( $value ) {
    return ( ! empty( $value ) ) ? 1 : 0;
}

}

new Pulpcovers_Modified_Posts_Feed();
